### ISSUE TITLE
Please add strong name to assembly

### ISSUE THREAD

**Issue by curelom** [vcaraulean/Caliburn.Micro.Telerik#11]
Please add a strong name to the assembly.  I can't add this project via nugget because it doesn't have it.  I have to pull from code and compile instead.  It would simplify things if you added a strong name.

**Comment by vcaraulean** [comment]
Signing often brings surprises & difficult constraints, that's why I prefer to not sign the assembly. 
See [discussion on nuget's forums](http://nuget.codeplex.com/discussions/247827) about signing. 

In your case you can copy over the few classes with conventions and other stuff directly in your project and ditch the dependency on nuget package.
